# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/glenn/yojimbo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/glenn/yojimbo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/glenn/yojimbo/CMakeFiles /Users/glenn/yojimbo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/glenn/yojimbo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/glenn/yojimbo/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sodium-builtin

# Build rule for target.
sodium-builtin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sodium-builtin
.PHONY : sodium-builtin

# fast build rule for target.
sodium-builtin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sodium-builtin.dir/build.make CMakeFiles/sodium-builtin.dir/build
.PHONY : sodium-builtin/fast

#=============================================================================
# Target rules for targets named netcode

# Build rule for target.
netcode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 netcode
.PHONY : netcode

# fast build rule for target.
netcode/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netcode.dir/build.make CMakeFiles/netcode.dir/build
.PHONY : netcode/fast

#=============================================================================
# Target rules for targets named reliable

# Build rule for target.
reliable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reliable
.PHONY : reliable

# fast build rule for target.
reliable/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reliable.dir/build.make CMakeFiles/reliable.dir/build
.PHONY : reliable/fast

#=============================================================================
# Target rules for targets named tlsf

# Build rule for target.
tlsf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tlsf
.PHONY : tlsf

# fast build rule for target.
tlsf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tlsf.dir/build.make CMakeFiles/tlsf.dir/build
.PHONY : tlsf/fast

#=============================================================================
# Target rules for targets named yojimbo

# Build rule for target.
yojimbo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yojimbo
.PHONY : yojimbo

# fast build rule for target.
yojimbo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/build
.PHONY : yojimbo/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named loopback

# Build rule for target.
loopback: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 loopback
.PHONY : loopback

# fast build rule for target.
loopback/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopback.dir/build.make CMakeFiles/loopback.dir/build
.PHONY : loopback/fast

#=============================================================================
# Target rules for targets named soak

# Build rule for target.
soak: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 soak
.PHONY : soak

# fast build rule for target.
soak/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soak.dir/build.make CMakeFiles/soak.dir/build
.PHONY : soak/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

client.o: client.cpp.o
.PHONY : client.o

# target to build an object file
client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.cpp.o
.PHONY : client.cpp.o

client.i: client.cpp.i
.PHONY : client.i

# target to preprocess a source file
client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.cpp.i
.PHONY : client.cpp.i

client.s: client.cpp.s
.PHONY : client.s

# target to generate assembly for a file
client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/client.cpp.s
.PHONY : client.cpp.s

loopback.o: loopback.cpp.o
.PHONY : loopback.o

# target to build an object file
loopback.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopback.dir/build.make CMakeFiles/loopback.dir/loopback.cpp.o
.PHONY : loopback.cpp.o

loopback.i: loopback.cpp.i
.PHONY : loopback.i

# target to preprocess a source file
loopback.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopback.dir/build.make CMakeFiles/loopback.dir/loopback.cpp.i
.PHONY : loopback.cpp.i

loopback.s: loopback.cpp.s
.PHONY : loopback.s

# target to generate assembly for a file
loopback.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/loopback.dir/build.make CMakeFiles/loopback.dir/loopback.cpp.s
.PHONY : loopback.cpp.s

netcode/netcode.o: netcode/netcode.c.o
.PHONY : netcode/netcode.o

# target to build an object file
netcode/netcode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netcode.dir/build.make CMakeFiles/netcode.dir/netcode/netcode.c.o
.PHONY : netcode/netcode.c.o

netcode/netcode.i: netcode/netcode.c.i
.PHONY : netcode/netcode.i

# target to preprocess a source file
netcode/netcode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netcode.dir/build.make CMakeFiles/netcode.dir/netcode/netcode.c.i
.PHONY : netcode/netcode.c.i

netcode/netcode.s: netcode/netcode.c.s
.PHONY : netcode/netcode.s

# target to generate assembly for a file
netcode/netcode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/netcode.dir/build.make CMakeFiles/netcode.dir/netcode/netcode.c.s
.PHONY : netcode/netcode.c.s

reliable/reliable.o: reliable/reliable.c.o
.PHONY : reliable/reliable.o

# target to build an object file
reliable/reliable.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reliable.dir/build.make CMakeFiles/reliable.dir/reliable/reliable.c.o
.PHONY : reliable/reliable.c.o

reliable/reliable.i: reliable/reliable.c.i
.PHONY : reliable/reliable.i

# target to preprocess a source file
reliable/reliable.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reliable.dir/build.make CMakeFiles/reliable.dir/reliable/reliable.c.i
.PHONY : reliable/reliable.c.i

reliable/reliable.s: reliable/reliable.c.s
.PHONY : reliable/reliable.s

# target to generate assembly for a file
reliable/reliable.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reliable.dir/build.make CMakeFiles/reliable.dir/reliable/reliable.c.s
.PHONY : reliable/reliable.c.s

server.o: server.cpp.o
.PHONY : server.o

# target to build an object file
server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.cpp.o
.PHONY : server.cpp.o

server.i: server.cpp.i
.PHONY : server.i

# target to preprocess a source file
server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.cpp.i
.PHONY : server.cpp.i

server.s: server.cpp.s
.PHONY : server.s

# target to generate assembly for a file
server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/server.cpp.s
.PHONY : server.cpp.s

soak.o: soak.cpp.o
.PHONY : soak.o

# target to build an object file
soak.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soak.dir/build.make CMakeFiles/soak.dir/soak.cpp.o
.PHONY : soak.cpp.o

soak.i: soak.cpp.i
.PHONY : soak.i

# target to preprocess a source file
soak.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soak.dir/build.make CMakeFiles/soak.dir/soak.cpp.i
.PHONY : soak.cpp.i

soak.s: soak.cpp.s
.PHONY : soak.s

# target to generate assembly for a file
soak.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soak.dir/build.make CMakeFiles/soak.dir/soak.cpp.s
.PHONY : soak.cpp.s

sodium/sodium.o: sodium/sodium.c.o
.PHONY : sodium/sodium.o

# target to build an object file
sodium/sodium.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sodium-builtin.dir/build.make CMakeFiles/sodium-builtin.dir/sodium/sodium.c.o
.PHONY : sodium/sodium.c.o

sodium/sodium.i: sodium/sodium.c.i
.PHONY : sodium/sodium.i

# target to preprocess a source file
sodium/sodium.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sodium-builtin.dir/build.make CMakeFiles/sodium-builtin.dir/sodium/sodium.c.i
.PHONY : sodium/sodium.c.i

sodium/sodium.s: sodium/sodium.c.s
.PHONY : sodium/sodium.s

# target to generate assembly for a file
sodium/sodium.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sodium-builtin.dir/build.make CMakeFiles/sodium-builtin.dir/sodium/sodium.c.s
.PHONY : sodium/sodium.c.s

source/yojimbo.o: source/yojimbo.cpp.o
.PHONY : source/yojimbo.o

# target to build an object file
source/yojimbo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo.cpp.o
.PHONY : source/yojimbo.cpp.o

source/yojimbo.i: source/yojimbo.cpp.i
.PHONY : source/yojimbo.i

# target to preprocess a source file
source/yojimbo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo.cpp.i
.PHONY : source/yojimbo.cpp.i

source/yojimbo.s: source/yojimbo.cpp.s
.PHONY : source/yojimbo.s

# target to generate assembly for a file
source/yojimbo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo.cpp.s
.PHONY : source/yojimbo.cpp.s

source/yojimbo_address.o: source/yojimbo_address.cpp.o
.PHONY : source/yojimbo_address.o

# target to build an object file
source/yojimbo_address.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_address.cpp.o
.PHONY : source/yojimbo_address.cpp.o

source/yojimbo_address.i: source/yojimbo_address.cpp.i
.PHONY : source/yojimbo_address.i

# target to preprocess a source file
source/yojimbo_address.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_address.cpp.i
.PHONY : source/yojimbo_address.cpp.i

source/yojimbo_address.s: source/yojimbo_address.cpp.s
.PHONY : source/yojimbo_address.s

# target to generate assembly for a file
source/yojimbo_address.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_address.cpp.s
.PHONY : source/yojimbo_address.cpp.s

source/yojimbo_allocator.o: source/yojimbo_allocator.cpp.o
.PHONY : source/yojimbo_allocator.o

# target to build an object file
source/yojimbo_allocator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_allocator.cpp.o
.PHONY : source/yojimbo_allocator.cpp.o

source/yojimbo_allocator.i: source/yojimbo_allocator.cpp.i
.PHONY : source/yojimbo_allocator.i

# target to preprocess a source file
source/yojimbo_allocator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_allocator.cpp.i
.PHONY : source/yojimbo_allocator.cpp.i

source/yojimbo_allocator.s: source/yojimbo_allocator.cpp.s
.PHONY : source/yojimbo_allocator.s

# target to generate assembly for a file
source/yojimbo_allocator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_allocator.cpp.s
.PHONY : source/yojimbo_allocator.cpp.s

source/yojimbo_base_client.o: source/yojimbo_base_client.cpp.o
.PHONY : source/yojimbo_base_client.o

# target to build an object file
source/yojimbo_base_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_base_client.cpp.o
.PHONY : source/yojimbo_base_client.cpp.o

source/yojimbo_base_client.i: source/yojimbo_base_client.cpp.i
.PHONY : source/yojimbo_base_client.i

# target to preprocess a source file
source/yojimbo_base_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_base_client.cpp.i
.PHONY : source/yojimbo_base_client.cpp.i

source/yojimbo_base_client.s: source/yojimbo_base_client.cpp.s
.PHONY : source/yojimbo_base_client.s

# target to generate assembly for a file
source/yojimbo_base_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_base_client.cpp.s
.PHONY : source/yojimbo_base_client.cpp.s

source/yojimbo_base_server.o: source/yojimbo_base_server.cpp.o
.PHONY : source/yojimbo_base_server.o

# target to build an object file
source/yojimbo_base_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_base_server.cpp.o
.PHONY : source/yojimbo_base_server.cpp.o

source/yojimbo_base_server.i: source/yojimbo_base_server.cpp.i
.PHONY : source/yojimbo_base_server.i

# target to preprocess a source file
source/yojimbo_base_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_base_server.cpp.i
.PHONY : source/yojimbo_base_server.cpp.i

source/yojimbo_base_server.s: source/yojimbo_base_server.cpp.s
.PHONY : source/yojimbo_base_server.s

# target to generate assembly for a file
source/yojimbo_base_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_base_server.cpp.s
.PHONY : source/yojimbo_base_server.cpp.s

source/yojimbo_channel.o: source/yojimbo_channel.cpp.o
.PHONY : source/yojimbo_channel.o

# target to build an object file
source/yojimbo_channel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_channel.cpp.o
.PHONY : source/yojimbo_channel.cpp.o

source/yojimbo_channel.i: source/yojimbo_channel.cpp.i
.PHONY : source/yojimbo_channel.i

# target to preprocess a source file
source/yojimbo_channel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_channel.cpp.i
.PHONY : source/yojimbo_channel.cpp.i

source/yojimbo_channel.s: source/yojimbo_channel.cpp.s
.PHONY : source/yojimbo_channel.s

# target to generate assembly for a file
source/yojimbo_channel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_channel.cpp.s
.PHONY : source/yojimbo_channel.cpp.s

source/yojimbo_client.o: source/yojimbo_client.cpp.o
.PHONY : source/yojimbo_client.o

# target to build an object file
source/yojimbo_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_client.cpp.o
.PHONY : source/yojimbo_client.cpp.o

source/yojimbo_client.i: source/yojimbo_client.cpp.i
.PHONY : source/yojimbo_client.i

# target to preprocess a source file
source/yojimbo_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_client.cpp.i
.PHONY : source/yojimbo_client.cpp.i

source/yojimbo_client.s: source/yojimbo_client.cpp.s
.PHONY : source/yojimbo_client.s

# target to generate assembly for a file
source/yojimbo_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_client.cpp.s
.PHONY : source/yojimbo_client.cpp.s

source/yojimbo_connection.o: source/yojimbo_connection.cpp.o
.PHONY : source/yojimbo_connection.o

# target to build an object file
source/yojimbo_connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_connection.cpp.o
.PHONY : source/yojimbo_connection.cpp.o

source/yojimbo_connection.i: source/yojimbo_connection.cpp.i
.PHONY : source/yojimbo_connection.i

# target to preprocess a source file
source/yojimbo_connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_connection.cpp.i
.PHONY : source/yojimbo_connection.cpp.i

source/yojimbo_connection.s: source/yojimbo_connection.cpp.s
.PHONY : source/yojimbo_connection.s

# target to generate assembly for a file
source/yojimbo_connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_connection.cpp.s
.PHONY : source/yojimbo_connection.cpp.s

source/yojimbo_network_simulator.o: source/yojimbo_network_simulator.cpp.o
.PHONY : source/yojimbo_network_simulator.o

# target to build an object file
source/yojimbo_network_simulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_network_simulator.cpp.o
.PHONY : source/yojimbo_network_simulator.cpp.o

source/yojimbo_network_simulator.i: source/yojimbo_network_simulator.cpp.i
.PHONY : source/yojimbo_network_simulator.i

# target to preprocess a source file
source/yojimbo_network_simulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_network_simulator.cpp.i
.PHONY : source/yojimbo_network_simulator.cpp.i

source/yojimbo_network_simulator.s: source/yojimbo_network_simulator.cpp.s
.PHONY : source/yojimbo_network_simulator.s

# target to generate assembly for a file
source/yojimbo_network_simulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_network_simulator.cpp.s
.PHONY : source/yojimbo_network_simulator.cpp.s

source/yojimbo_platform.o: source/yojimbo_platform.cpp.o
.PHONY : source/yojimbo_platform.o

# target to build an object file
source/yojimbo_platform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_platform.cpp.o
.PHONY : source/yojimbo_platform.cpp.o

source/yojimbo_platform.i: source/yojimbo_platform.cpp.i
.PHONY : source/yojimbo_platform.i

# target to preprocess a source file
source/yojimbo_platform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_platform.cpp.i
.PHONY : source/yojimbo_platform.cpp.i

source/yojimbo_platform.s: source/yojimbo_platform.cpp.s
.PHONY : source/yojimbo_platform.s

# target to generate assembly for a file
source/yojimbo_platform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_platform.cpp.s
.PHONY : source/yojimbo_platform.cpp.s

source/yojimbo_reliable_ordered_channel.o: source/yojimbo_reliable_ordered_channel.cpp.o
.PHONY : source/yojimbo_reliable_ordered_channel.o

# target to build an object file
source/yojimbo_reliable_ordered_channel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_reliable_ordered_channel.cpp.o
.PHONY : source/yojimbo_reliable_ordered_channel.cpp.o

source/yojimbo_reliable_ordered_channel.i: source/yojimbo_reliable_ordered_channel.cpp.i
.PHONY : source/yojimbo_reliable_ordered_channel.i

# target to preprocess a source file
source/yojimbo_reliable_ordered_channel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_reliable_ordered_channel.cpp.i
.PHONY : source/yojimbo_reliable_ordered_channel.cpp.i

source/yojimbo_reliable_ordered_channel.s: source/yojimbo_reliable_ordered_channel.cpp.s
.PHONY : source/yojimbo_reliable_ordered_channel.s

# target to generate assembly for a file
source/yojimbo_reliable_ordered_channel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_reliable_ordered_channel.cpp.s
.PHONY : source/yojimbo_reliable_ordered_channel.cpp.s

source/yojimbo_server.o: source/yojimbo_server.cpp.o
.PHONY : source/yojimbo_server.o

# target to build an object file
source/yojimbo_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_server.cpp.o
.PHONY : source/yojimbo_server.cpp.o

source/yojimbo_server.i: source/yojimbo_server.cpp.i
.PHONY : source/yojimbo_server.i

# target to preprocess a source file
source/yojimbo_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_server.cpp.i
.PHONY : source/yojimbo_server.cpp.i

source/yojimbo_server.s: source/yojimbo_server.cpp.s
.PHONY : source/yojimbo_server.s

# target to generate assembly for a file
source/yojimbo_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_server.cpp.s
.PHONY : source/yojimbo_server.cpp.s

source/yojimbo_unreliable_unordered_channel.o: source/yojimbo_unreliable_unordered_channel.cpp.o
.PHONY : source/yojimbo_unreliable_unordered_channel.o

# target to build an object file
source/yojimbo_unreliable_unordered_channel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_unreliable_unordered_channel.cpp.o
.PHONY : source/yojimbo_unreliable_unordered_channel.cpp.o

source/yojimbo_unreliable_unordered_channel.i: source/yojimbo_unreliable_unordered_channel.cpp.i
.PHONY : source/yojimbo_unreliable_unordered_channel.i

# target to preprocess a source file
source/yojimbo_unreliable_unordered_channel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_unreliable_unordered_channel.cpp.i
.PHONY : source/yojimbo_unreliable_unordered_channel.cpp.i

source/yojimbo_unreliable_unordered_channel.s: source/yojimbo_unreliable_unordered_channel.cpp.s
.PHONY : source/yojimbo_unreliable_unordered_channel.s

# target to generate assembly for a file
source/yojimbo_unreliable_unordered_channel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_unreliable_unordered_channel.cpp.s
.PHONY : source/yojimbo_unreliable_unordered_channel.cpp.s

source/yojimbo_utils.o: source/yojimbo_utils.cpp.o
.PHONY : source/yojimbo_utils.o

# target to build an object file
source/yojimbo_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_utils.cpp.o
.PHONY : source/yojimbo_utils.cpp.o

source/yojimbo_utils.i: source/yojimbo_utils.cpp.i
.PHONY : source/yojimbo_utils.i

# target to preprocess a source file
source/yojimbo_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_utils.cpp.i
.PHONY : source/yojimbo_utils.cpp.i

source/yojimbo_utils.s: source/yojimbo_utils.cpp.s
.PHONY : source/yojimbo_utils.s

# target to generate assembly for a file
source/yojimbo_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yojimbo.dir/build.make CMakeFiles/yojimbo.dir/source/yojimbo_utils.cpp.s
.PHONY : source/yojimbo_utils.cpp.s

test.o: test.cpp.o
.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i
.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s
.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test.cpp.s
.PHONY : test.cpp.s

tlsf/tlsf.o: tlsf/tlsf.c.o
.PHONY : tlsf/tlsf.o

# target to build an object file
tlsf/tlsf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tlsf.dir/build.make CMakeFiles/tlsf.dir/tlsf/tlsf.c.o
.PHONY : tlsf/tlsf.c.o

tlsf/tlsf.i: tlsf/tlsf.c.i
.PHONY : tlsf/tlsf.i

# target to preprocess a source file
tlsf/tlsf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tlsf.dir/build.make CMakeFiles/tlsf.dir/tlsf/tlsf.c.i
.PHONY : tlsf/tlsf.c.i

tlsf/tlsf.s: tlsf/tlsf.c.s
.PHONY : tlsf/tlsf.s

# target to generate assembly for a file
tlsf/tlsf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tlsf.dir/build.make CMakeFiles/tlsf.dir/tlsf/tlsf.c.s
.PHONY : tlsf/tlsf.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... client"
	@echo "... loopback"
	@echo "... netcode"
	@echo "... reliable"
	@echo "... server"
	@echo "... soak"
	@echo "... sodium-builtin"
	@echo "... test"
	@echo "... tlsf"
	@echo "... yojimbo"
	@echo "... client.o"
	@echo "... client.i"
	@echo "... client.s"
	@echo "... loopback.o"
	@echo "... loopback.i"
	@echo "... loopback.s"
	@echo "... netcode/netcode.o"
	@echo "... netcode/netcode.i"
	@echo "... netcode/netcode.s"
	@echo "... reliable/reliable.o"
	@echo "... reliable/reliable.i"
	@echo "... reliable/reliable.s"
	@echo "... server.o"
	@echo "... server.i"
	@echo "... server.s"
	@echo "... soak.o"
	@echo "... soak.i"
	@echo "... soak.s"
	@echo "... sodium/sodium.o"
	@echo "... sodium/sodium.i"
	@echo "... sodium/sodium.s"
	@echo "... source/yojimbo.o"
	@echo "... source/yojimbo.i"
	@echo "... source/yojimbo.s"
	@echo "... source/yojimbo_address.o"
	@echo "... source/yojimbo_address.i"
	@echo "... source/yojimbo_address.s"
	@echo "... source/yojimbo_allocator.o"
	@echo "... source/yojimbo_allocator.i"
	@echo "... source/yojimbo_allocator.s"
	@echo "... source/yojimbo_base_client.o"
	@echo "... source/yojimbo_base_client.i"
	@echo "... source/yojimbo_base_client.s"
	@echo "... source/yojimbo_base_server.o"
	@echo "... source/yojimbo_base_server.i"
	@echo "... source/yojimbo_base_server.s"
	@echo "... source/yojimbo_channel.o"
	@echo "... source/yojimbo_channel.i"
	@echo "... source/yojimbo_channel.s"
	@echo "... source/yojimbo_client.o"
	@echo "... source/yojimbo_client.i"
	@echo "... source/yojimbo_client.s"
	@echo "... source/yojimbo_connection.o"
	@echo "... source/yojimbo_connection.i"
	@echo "... source/yojimbo_connection.s"
	@echo "... source/yojimbo_network_simulator.o"
	@echo "... source/yojimbo_network_simulator.i"
	@echo "... source/yojimbo_network_simulator.s"
	@echo "... source/yojimbo_platform.o"
	@echo "... source/yojimbo_platform.i"
	@echo "... source/yojimbo_platform.s"
	@echo "... source/yojimbo_reliable_ordered_channel.o"
	@echo "... source/yojimbo_reliable_ordered_channel.i"
	@echo "... source/yojimbo_reliable_ordered_channel.s"
	@echo "... source/yojimbo_server.o"
	@echo "... source/yojimbo_server.i"
	@echo "... source/yojimbo_server.s"
	@echo "... source/yojimbo_unreliable_unordered_channel.o"
	@echo "... source/yojimbo_unreliable_unordered_channel.i"
	@echo "... source/yojimbo_unreliable_unordered_channel.s"
	@echo "... source/yojimbo_utils.o"
	@echo "... source/yojimbo_utils.i"
	@echo "... source/yojimbo_utils.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
	@echo "... tlsf/tlsf.o"
	@echo "... tlsf/tlsf.i"
	@echo "... tlsf/tlsf.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/glenn/yojimbo/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

