# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  test_config = debug_x64
  network_info_config = debug_x64
  yojimbo_config = debug_x64
  client_config = debug_x64
  server_config = debug_x64
  client_server_config = debug_x64
endif
ifeq ($(config),release_x64)
  test_config = release_x64
  network_info_config = release_x64
  yojimbo_config = release_x64
  client_config = release_x64
  server_config = release_x64
  client_server_config = release_x64
endif

PROJECTS := test network_info yojimbo client server client_server

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

test: yojimbo
ifneq (,$(test_config))
	@echo "==== Building test ($(test_config)) ===="
	@${MAKE} --no-print-directory -C . -f test.make config=$(test_config)
endif

network_info: yojimbo
ifneq (,$(network_info_config))
	@echo "==== Building network_info ($(network_info_config)) ===="
	@${MAKE} --no-print-directory -C . -f network_info.make config=$(network_info_config)
endif

yojimbo:
ifneq (,$(yojimbo_config))
	@echo "==== Building yojimbo ($(yojimbo_config)) ===="
	@${MAKE} --no-print-directory -C . -f yojimbo.make config=$(yojimbo_config)
endif

client: yojimbo
ifneq (,$(client_config))
	@echo "==== Building client ($(client_config)) ===="
	@${MAKE} --no-print-directory -C . -f client.make config=$(client_config)
endif

server: yojimbo
ifneq (,$(server_config))
	@echo "==== Building server ($(server_config)) ===="
	@${MAKE} --no-print-directory -C . -f server.make config=$(server_config)
endif

client_server: yojimbo
ifneq (,$(client_server_config))
	@echo "==== Building client_server ($(client_server_config)) ===="
	@${MAKE} --no-print-directory -C . -f client_server.make config=$(client_server_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f test.make clean
	@${MAKE} --no-print-directory -C . -f network_info.make clean
	@${MAKE} --no-print-directory -C . -f yojimbo.make clean
	@${MAKE} --no-print-directory -C . -f client.make clean
	@${MAKE} --no-print-directory -C . -f server.make clean
	@${MAKE} --no-print-directory -C . -f client_server.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  release_x64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   test"
	@echo "   network_info"
	@echo "   yojimbo"
	@echo "   client"
	@echo "   server"
	@echo "   client_server"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"